# 데이터 전처리
### ✔ 결측값, Null 값 허용 안됨
- 피처 값 중 Null 값이 얼마 되지 않는다면 피처의 평균값 등으로 대체
- 피처 값 중 Null 값이 대부분이라면 드롭
- 하지만 해당 피처가 중요도가 높고 Null을 평균값으로 대체 할 경우 왜곡이 심하다면 정밀한 대체 값을 선정

### ✔ 문자열 값을 입력값으로 허용하지 않는다
- 모든 문자열 값은 인코딩 해서 숫자 형으로 변환해야 한다
- 일반적으로 카테고리형 피처와 텍스트형 피처를 의미
- 텍스트형 피처는 백터화(feature vectorization) 기법으로 백터화
- 불필요하다면 삭제

## 1. 데이터 인코딩

### [레이블 인코딩]
- 카테고리 피처를 코드형 숫자 값으로 변환하는 것
- 주의 해야 할 점은 '01','02' 같은 코드 값 역시 문자열이므로 변환 필요
- 선형회귀와 같은 알고리즘에는 적용하지 않아야 한다

In [1]:
# 사이킷런의 레이블 인코딩은 LabelEncoder 클래스로 구현
# LabelEncoder를 객체로 생성한 후 fit()과 transform()을 호출해 수행
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 : ', labels)

인코딩 변환값 :  [0 1 4 5 3 3 2 2]


In [4]:
# 문자열값이 어떤 숫자값으로 인코딩 됐는지 속성값을 알고 싶으면 classes_ 
print('인코딩 클래스 : ', encoder.classes_)

인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [7]:
# inverse_transform()을 이용해 인코딩 된 값을 디코딩 할 수 있다
print('디코딩 원본 값 : ', encoder.inverse_transform([0,1,4,5,3,3,2,2]))

디코딩 원본 값 :  ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


✔ 레이블 인코딩은 간단하게 문자열 값을 숫자형 카테고리 값으로 변환

✔ 숫자 값의 경우 크고 작음에 대한 특성이 작용하기 때문에 ML 알고리즘에서 가중치가 더 부여 되거나 더 중요하게 인식할 수 있어서 선형회귀에서는 사용 안함

### [ 원-핫 인코딩 ]
- 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해달하는 칼럼에만 1을 표시
- 나머지 칼럼에는 0을 표시하는 방식
- 즉, 행 형태로 돼 있는 피처의 고유 값을 열 형태로 차원을 변환 한뒤,고유값에 해당하는 컬럼만 1을 표시하고 나머지는 0
- LabelEncoder와 다르게 주의할 점이 있다. 원-핫 인코딩으로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환돼야 한다
- 즉, 레이블 인코딩으로 숫자형으로 변환 한 뒤 원-핫 인코딩 변환
- 입력 값으로 2차원 데이터가 필요하다

⭐ get_dummies()를 이용하면 문자열을 숫자형으로 변환 하지 않아도 됨

##### 일반 OneHotEncoder

In [9]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자 값으로 변환을 위해 LebelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

In [12]:
# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)
print('데이터 차원 : ',oh_labels.ndim)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)
데이터 차원 :  2


✔ 8개의 레코드와 1개의 컬럼을 가진 원본 데이터가 8개의 레코드와 6개의 컬럼을 가진 데이터로 변환 됐다

##### 판다스 get_dummies() API

In [13]:
import pandas as pd

df = pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

✔ get_dummies()를 이용하면 숫자형 값으로 변환 없이 바로 변환 가능

## 2. 피처 스케일링과 정규화
#### 피처 스케일링
- 서로 다은 변수의 값 범위를 일정한 수준으로 맞추는 작업
- 대표적인 방법으로 표준화(Standardization),정규화(Normalization)

✔ 표준화
- 데이터의 피처 각각이 평균 0, 분산(var) 1인 **가우시안 정규분포**를 가진 값으로 변환 하는 것

✔ 정규화
- 서로 다른 크기를 통일하기 위해 크기를 변환해주는 개념
- 예로 km 와 원 단위 즉, 개별 데이터의 크기를 모두 똑같은 단위로 변경

✔ 백터 정규화
- 선형대수 개념의 정규화
- 사이킷런의 Normarlizaer 모듈은 선형대수에서의 정규화 개념이 적용
- 개별 백터의 크기를 맞추기 위해 변환하는 것을 의미

⭐ 혼선 방지를 위해 표준화와 정규화를 피처스케일링으로 통칭, 선현대수 정규화를 백터 정규화로 지칭


-----------------------------------------------------------------------------

### [ StandardScaler ]
- 표준화를 쉽게 지원하기 위한 클래스
- 가우시안 정규 분포를 가질 수 있도록 데이터를 변환하는 것은 몇몇 알고리즘에서 매우 중요
- 선형회귀(Linear Regression), 로지스틱회귀(Logistic Regression)는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현됐기 때문에 사전에 표준화를 적용하는 것이 예측 성능 향상에 중요한 요소가 될 수 있음


In [17]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트 로딩 하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data,columns=iris.feature_names)

print('feature 들의 평균값')
print(iris_df.mean())
print('\nfeature 들의 분산값')
print(iris_df.var())

feature 들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [18]:
# StandardScaler를 이용해 각 피처를 한번에 표준화
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터 세트 변환, fit_transform()
iris_scaled = scaler.fit_transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 ndarray로 반환돼 이를 DataFrame으로 반환
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)

print('feature 들의 평균값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산값')
print(iris_df_scaled.var())

feature 들의 평균값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


✔ 모든 컬럼 값이 평균이 0에 아주 가까운 값으로 변환

✔ 분산은 1에 아주 가까운 값으로 변환됐음을 알 수  있다

### [ MinMaxScaler ]
- 데이터 값을 0과 1사이의 범위 값으로 변환(음수값이 있으면 -1에서 1값으로 변환)
- 데이터의 분포가 가우시안 분포가 아닐경우에 적용

In [21]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 세트 변환
iris_scaled = scaler.fit_transform(iris_df)

# ndarray로 변환 돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(iris_scaled,columns=iris.feature_names)

print('feature 들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature 들의 최댓값')
print(iris_df_scaled.max())

feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature 들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


✔ 모든 피처에서 0과 1 사이의 값으로 변환되는 스케일링이 적용

## 학습 데이터와 테스트 데이터의 스케일링 변환시 유의점
- 학습 데이터와 테스트 데이터를 분리를 먼저 했을 경우
- 학습 데이터는 fit() transform()로 스케일링
- 테스트 데이터는 transform()으로만 스케일링 해야한다 fit()은 절대 금지
- 테스트 데이터로 다시 새로운 스케일링 기준 정보를 만들게 되면 학습 데이터와 테스트 데이터의 스케일링 기준 정보가 서로 달라지기 때문에 올바른 예측 결과가를 도출하지 못 한다

⭐ 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
